eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${IP_ADDRESS}
    hostname: ${HOST_NAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:9001/eureka/}

spring:
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    http:
      path: /graphql
      
management:
  metrics:
    binders:
      system:
        enabled: false